api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        pagination_items_per_page: 10 # Default items per page value
        pagination_maximum_items_per_page: 20 # Maximum items per page
        pagination_client_items_per_page: true # Client side items per page request enabled

        # Enabled : disable count query / don't have hydra:last and hydra:totalItems anymore
        # Very usefull for big projects w/ big databases ans big requests
        # Default value : false
        pagination_partial: true 
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage # CLient side items per page parameter name
