vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: 
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' }