version: "3.8"

services:

    database:
        container_name: database
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - '4306:3306'
        volumes:
            - ./docker/mysql:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        environment:
            PMA_HOST: database
        depends_on:
            - database
        ports:
            - 8082:80

    php:
        container_name: php
        restart: always
        build:
            context: ./api
        working_dir: /var/www/symfony_docker
        volumes:
            - ./api/:/var/www/symfony_docker
        depends_on:
            - database

    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./api/:/var/www/symfony_docker
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php 
        labels:
            # enable traefik
            - traefik.enable=true
            # config for HTTPS
            - traefik.http.routers.gameapi_ssl.tls=true
            - traefik.http.routers.gameapi_ssl.rule=Host(`gameapi`)
            - traefik.http.routers.gameapi_ssl.entrypoints=web-secure
    
    node:
        container_name: node
        restart: always
        build:
            context: ./client
        volumes:
            - ./client/:/app
            - /app/node_modules
        depends_on:
            - database
        labels:
            # enable traefik
            - traefik.enable=true
            - traefik.http.services.gameclient.loadbalancer.server.port=3000
            # config for HTTPS
            - traefik.http.routers.gameclient_ssl.tls=true
            - traefik.http.routers.gameclient_ssl.rule=Host(`gameclient`)
            - traefik.http.routers.gameclient_ssl.entrypoints=web-secure

    traefik:
        container_name: traefik
        image: traefik:latest
        restart: always
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        command: 
            # Docker swarm configuration
            - "--providers.docker"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock:ro
            # Traefik conf file
            - ./docker/traefik:/etc/traefik:ro
            # Certs conf file
            - ./docker/traefik/certs:/etc/certs:ro
        labels:
            - traefik.enable=true
            - traefik.http.routers.dashboard.rule=Host(`dashboard`)
            - traefik.http.routers.traefik=true
            
