version: "3.8"

services:

    database:
        container_name: database
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - '4306:3306'
        volumes:
            - ./docker/mysql:/var/lib/mysql

    php:
        container_name: php
        restart: always
        build:
            context: ./docker/php
        ports:
            - '9000:9000'
        volumes:
            - ../GameApi/:/var/www/symfony_docker
        depends_on:
            - database

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        environment:
            PMA_HOST: database
        depends_on:
            - database
        ports:
            - 8081:80

    nginx:
        container_name: nginx
        restart: always
        image: nginx:stable-alpine
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ../GameApi/:/var/www/symfony_docker
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/certs:/etc/ssl/certs
        depends_on:
            - php
            - database