version: "3.8"

services:

    database:
        container_name: database
        image: mysql:8.0
        restart: always
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - '4306:3306'
        volumes:
            - ./docker/mysql:/var/lib/mysql

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        environment:
            PMA_HOST: database
        depends_on:
            - database
        ports:
            - 8082:80

    php:
        container_name: php
        restart: always
        build:
            context: ./api
        working_dir: /var/www/symfony_docker
        volumes:
            - ./api/:/var/www/symfony_docker
        depends_on:
            - database

    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./api/:/var/www/symfony_docker
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/certs:/etc/ssl/certs
        links:
            - php 
        labels:
            - traefik.enable=true
            - "traefik.http.routers.gameapi.rule=Host(`gameapi`)"
            - "traefik.http.services.gameapi.loadbalancer.server.port=80"
    
    node:
        container_name: node
        restart: always
        build:
            context: ./client
        volumes:
            - ./client/:/app
            - /app/node_modules
        depends_on:
            - database
        labels:
            - traefik.enable=true
            - "traefik.http.routers.gameclient.rule=Host(`gameclient`)"
            - "traefik.http.services.gameclient.loadbalancer.server.port=3000"

    traefik:
        container_name: traefik
        image: traefik:latest
        restart: always
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
        command: 
            - "--api.insecure=true"
            - "--providers.docker"
            - "--entrypoints.web.address=:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./docker/traefik/traefik.yml:/etc/traefik/traefik.yml
        labels:
            - traefik.enable=true
            - "traefik.http.routers.dashboard.rule=Host(`dashboard`)"
